name: Mirror App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install root dependencies if any
    - name: Install root dependencies
      run: npm ci
      
    # Backend build steps
    - name: Install backend dependencies
      working-directory: ./mirror-backend
      run: npm ci
      
    - name: Check backend syntax
      working-directory: ./mirror-backend
      run: node -c server.js
    
    # Frontend build steps
    - name: Install frontend dependencies
      working-directory: ./mirror-frontend
      run: npm ci
    
    - name: Build frontend
      working-directory: ./mirror-frontend
      run: npm run build
    
    - name: Run frontend lint
      working-directory: ./mirror-frontend
      run: npm run lint
    
    # Unit tests steps
    - name: Install unit tests dependencies
      working-directory: ./unit-tests
      run: npm ci
    
    - name: Run unit tests
      working-directory: ./unit-tests
      run: npm test
      env:
        API_BASE_URL: http://localhost:3000
    
    # Selenium tests steps
    - name: Install Selenium test dependencies
      working-directory: ./selenium-tests
      run: npm ci
    
    # Setup Chrome for Selenium tests
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    # Start Backend server for Selenium tests
    - name: Start backend server
      working-directory: ./mirror-backend
      run: |
        nohup node server.js &
        echo $! > backend.pid
        sleep 5
      env:
        MONGODB_URI: mongodb://localhost:27017/mirror
        JWT_SECRET: test-jwt-secret
        PORT: 3000
    
    # Start Frontend server for Selenium tests
    - name: Start frontend server
      working-directory: ./mirror-frontend
      run: |
        nohup npm run dev &
        echo $! > frontend.pid
        sleep 10
      env:
        VITE_API_URL: http://localhost:3000
    
    # Run Selenium tests
    - name: Run Selenium tests
      working-directory: ./selenium-tests
      run: npm run test:login
      env:
        SELENIUM_REMOTE_URL: ''
        SELENIUM_BROWSER: chrome
        SELENIUM_HEADLESS: 'true'
        BASE_URL: http://localhost:5173
        API_URL: http://localhost:3000